plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('server/zebrakit.jar')
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

application {
    mainClass = project.hasProperty('agent') ? "lezhor.htw.zebrakit.agents.${project.getProperty('agent')}" : 'lezhor.htw.zebrakit.agents.Dummy'
}
