plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('server/zebrakit.jar')
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

application {
    mainClass = 'lezhor.htw.zebrakit.runtime.Main'
}
